### ISSUE TITLE
How to define a SWIFT_VERSION

### ISSUE THREAD

**Issue by cardozorobson** [espresso3389/flutter_pdf_render#10]
I'm developing an app, and for the first time i'm trying to run in a iOS device, when a run **pod install** i receive this error: 

- `pdf_render` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.

I'm using the version 0.57.1

**Comment by espresso3389** [comment]
If you are using Objective-C instead of Swift, you may have to edit your Podfile:

```Podfile
target 'Runner' do
  use_frameworks!  # required by simple_permission
  ...
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'  # required by simple_permission
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

The fragment above is from [IMPORTANT Note for iOS - flutter_inappwebview](https://pub.dev/packages/flutter_inappwebview#important-note-for-ios).

**Comment by o-julio** [comment]
I also needed to create an empty swift file through xcode, with a bridging header
