### ISSUE TITLE
[web] plugin not working

### ISSUE THREAD

**Issue by ezfuncreations** [espresso3389/flutter_pdf_render#11]
Hi.
Why is this plugin marked as working on flutter web on https://pub.dev/packages?
When i try to run PdfDocument.openData(whatever);
all i get is this in logs:
`MissingPluginException(No implementation found for method data on channel pdf_render)`
I skimmed through all commits and branches and none of them mention web as well.
Am i missing something?

**Comment by espresso3389** [comment]
Wow, I'm not sure why... I'll check my configs (yaml or... anything else?).

**Comment by espresso3389** [comment]
Releasing [0.57.2](https://pub.dev/packages/pdf_render/versions/0.57.2) not to be shown as WEB compatible.
