### ISSUE TITLE
Lack of support for Android Gradle Plugin 8

### ISSUE THREAD

**Issue by PerLycke** [espresso3389/flutter_pdf_render#128]
Thanks for a very useful plugin.

`android` block in build.gradle is missing the `namespace` property:

https://github.com/espresso3389/flutter_pdf_render/blob/72b79c3a5e8bdf095323cf3435f19bff425f7037/android/build.gradle#L27-L44

`namespace` is required in the android block in the build.gradle file in order to support Android Gradle Plugin 8+:

https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#namespace-dsl

Instructions on how to set it: https://developer.android.com/build/configure-app-module#set-namespace

**Comment by espresso3389** [comment]
Could you please create some PR for the issue? I'm not good at gradle :(

**Comment by espresso3389** [comment]
[1.4.2](https://pub.dev/packages/pdf_render/versions/1.4.2) has been just released!
