### ISSUE TITLE
java.io.FileNotFoundException

### ISSUE THREAD

**Issue by ChandraPrakashJangid** [espresso3389/flutter_pdf_render#14]
I am trying to read file from the device memory but it is returning me an error. Here it is:
`Error is PlatformException(error, Unsupported value: java.io.FileNotFoundException: flutter_assets//storage/emulated/0/Android/data/cn.wps.moffice_eng/.cache/KingsoftOffice/file/download/05ab545e-7efb-4083-9ee5-f4994862bde8/sample.pdf, null)
`

**Comment by espresso3389** [comment]
Oh, you may use PdfDocument.openAsset. Please use PdfDocument.openFile instead of it.
