### ISSUE TITLE
Publish latest changes?

### ISSUE THREAD

**Issue by rmerom** [espresso3389/flutter_pdf_render#145]
Hi there, seems like the last version was published [about 2 months ago](https://pub.dev/packages/pdf_render/versions), but since then an [important commit](https://github.com/espresso3389/flutter_pdf_render/commit/be374fa40f561cefc8dd0bc7b787b6127cb0e397) that unbreaks the code was committed. Any chance you could publish a new version with that change? 

Thank you for all the hard work!

**Comment by espresso3389** [comment]
[1.4.7](https://pub.dev/packages/pdf_render/versions/1.4.7) has released that contains long pended changes.
