### ISSUE TITLE
JumpTo specific page

### ISSUE THREAD

**Issue by kebsont** [espresso3389/flutter_pdf_render#15]
Hello, can we jump to specific page with getPage() ?

Can you share a snippet for jumping to a specific page when opening a PDF document ?

**Comment by espresso3389** [comment]
The new [PdfViewer](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets2/PdfViewer-class.html) has its own [PdfViewerController](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets2/PdfViewerController-class.html).
You can implement jump to specific page by the following code:

```dart
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    PdfViewerController controller;
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Pdf_render example app'),
        ),
        backgroundColor: Colors.grey,
        body: PdfViewer(
          assetName: 'assets/same.pdf'
          onViewerControllerInitialized: (c) { controller = c; },
        ),
        floatingActionButton: FloatingActionButton(..., onPressed: () => controller?.goToPage(pageNumber: 10))
      )
    );
  }
}
```
