### ISSUE TITLE
how to horiz. align page number

### ISSUE THREAD

**Issue by github-bianca** [espresso3389/flutter_pdf_render#20]
I would like to show it in bottom RIGHT corner of pages.
Possible ?

**Comment by espresso3389** [comment]
Do you mean "to show page number on the bottom right corner of pages"?
If so, `PdfViewer` has [buildPageOverlay](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets2/PdfViewer/buildPageOverlay.html) parameter that is called to build page overlay.
`PdfPageView`, `PdfDocumentLoader` has [pageBuilder](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets2/PdfPageBuilder.html).

**Comment by espresso3389** [comment]
The following fragment is a sample use and I guess it will work (didn't tested yet):

```dart
PdfViewer(
  assetName: 'assets/hello.pdf',
  buildPageOverlay: (context, pageNumber, rect) => Align(child: Text('$pageNumber'), alignment: Alignment.bottomRight),
)
```
