### ISSUE TITLE
No version of NDK matched

### ISSUE THREAD

**Issue by Sahmirzali** [espresso3389/flutter_pdf_render#23]
Hello. i run your example project. when i run this error happen. how can i solve ?

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':pdf_render'.
> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147, 21.3.6528147

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
Exception: Gradle task assembleDebug failed with exit code 1
```

**Comment by Sahmirzali** [comment]
problem solving : change - > `classpath 'com.android.tools.build:gradle:3.5.0'`

**Comment by aaqibism** [comment]
I am also facing this issue while compiling using Github Actions CI. I don't have this problem locally. Is there any other solution besides downgrading my Gradle version?

<details>
<summary>Terminal Output</summary>

Running Gradle task 'assembleDebug'...                          

FAILURE: Build failed with an exception.



* What went wrong:

A problem occurred configuring project ':pdf_render'.

> No version of NDK matched the requested version 21.0.6113669. Versions available locally: 21.3.6528147



* Try:

Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at help.gradle.org




BUILD FAILED in 1m 25s

Running Gradle task 'assembleDebug'...                             86.1s
Gradle task assembleDebug failed with exit code 1
Error: Process completed with exit code 1.

</details>

**Comment by espresso3389** [comment]
Yeah, I also sometimes hitting the issue and no solid fix for it...
On my own projects, I'm using the following version:

`classpath 'com.android.tools.build:gradle:3.5.4'`

**Comment by aaqibism** [comment]
@espresso3389 I managed to fix it by installing the specific ndk version that the error was complaining about using the following command. It works now no issue with Gradle 4.0.0.

`
- name: Install NDK
        run: echo "y" | sudo /usr/local/lib/android/sdk/tools/bin/sdkmanager --install "ndk;21.0.6113669" --sdk_root=${ANDROID_SDK_ROOT}

`
