### ISSUE TITLE
Network Support

### ISSUE THREAD

**Issue by kuntojirohan** [espresso3389/flutter_pdf_render#26]
This is a lovely plugin, awesome work! Can you please try to include the support to render pdf files by fetching them from network/url?

**Comment by sajanyamaha** [comment]
any plans for this enhancement ?

**Comment by espresso3389** [comment]
Using [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager), it is very easy to implement the feature. The code might be like the following fragment:

```dart
FutureBuilder<File>(
  future: DefaultCacheManager().getSingleFile(url),
  builder: (context, snapshot) => dataSnapshot.hasData ? PdfViewer.file(snapshot.data) : Container(/* some placeholder */)
)
```

Because the feature is so easy to implement and I don't make the plugin larger, I don't want to implement this on the plugin.

**Comment by espresso3389** [comment]
On 1.0.9, I updated [README.md](https://pub.dev/packages/pdf_render#missing-network-support) to explain the missing networking feature and also [the example code](https://github.com/espresso3389/flutter_pdf_render/blob/master/example/lib/main.dart#L37) has sample usage (for macOS but it also works on every platform).
