### ISSUE TITLE
Exception has occurred when fast scroll

### ISSUE THREAD

**Issue by pndaza** [espresso3389/flutter_pdf_render#28]
I try multipage view with ListView.builder.
It is grate.
But exception has occurred when scroll is too fast or when warp in draggalbe_scrollabar and drag scroll thumb.

Exception has occurred.
_AssertionError ('package:flutter/src/widgets/media_query.dart': Failed assertion: line 812 pos 12: 'context != null': is not true.)

**Comment by espresso3389** [comment]
Could you give me the full stack trace of the exception and/or more concrete sample?

**Comment by pndaza** [comment]
Same as your example expect scrollDriection. I try with vertical axis.

**Comment by pndaza** [comment]
wrap in [DraggableScrollbar](https://pub.dev/packages/draggable_scrollbar)

Slowly dragging is OK. Exception has occured only when dragging is too fast.

``` dart
Widget _multiPageView() {
    final ScrollController scrollController = ScrollController();
    return PdfDocumentLoader(
      assetName: 'assets/books/000126.pdf',
      documentBuilder: (context, pdfDocument, pageCount) =>
          DraggableScrollbar.arrows(
              controller: scrollController,
              child: ListView.builder(
                controller: scrollController,
                  itemCount: pageCount,
                  itemBuilder: (context, index) => Container(
                      margin: EdgeInsets.all(16),
                      padding: EdgeInsets.all(2),
                      color: Colors.black12,
                      child: PdfPageView(
                        pdfDocument: pdfDocument,
                        pageNumber: index + 1,
                      )))),
    );
  }
```

**Comment by pndaza** [comment]
It's Ok at version 1.0.8
