### ISSUE TITLE
Rendering black screen in iOS (simulator)

### ISSUE THREAD

**Issue by isorensen** [espresso3389/flutter_pdf_render#3]
Dear developer, first of all, congratulations on the effort.
I've been searching for a simple pdf viewer for flutter, but I couldn't get it to work. In flutter_pdf_render example, I just built it as it is in GitHub, and it gives me black screens, as shown in image below.

<img width="309" alt="Captura de Tela 2019-09-07 às 20 39 20" src="https://user-images.githubusercontent.com/3399976/64481302-e9974e00-d1af-11e9-84bd-119599053362.png">

Flutter doctor:

> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G95, locale pt-BR)
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
> [✓] Xcode - develop for iOS and macOS (Xcode 10.3)
> [✓] iOS tools - develop for iOS devices
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.35.0)
> [✓] Connected device (1 available)
> 
> • No issues found!
> 

I appreciate for your comments.
Regards

**Comment by espresso3389** [comment]
This is actually an issue on Flutter's Texture but I think I can have some workaround for it.

video_player module has the identical issue anyway:
https://github.com/flutter/flutter/issues/14647

**Comment by espresso3389** [comment]
0.57.0 introduces compatibility rendering on iOS simulator, that is "emulating" rendering on physical devices. It's not perfect and may work differently to the real devices.
