### ISSUE TITLE
⛔ MissingPluginException(No implementation found for method asset on channel pdf_render)

### ISSUE THREAD

**Issue by maxzod** [espresso3389/flutter_pdf_render#37]
I/flutter (29464): │ ⛔ MissingPluginException(No implementation found for method asset on channel pdf_render)
- OS: Android
- Version : 11
- Flutter (Channel stable, 2.0.3)
code
```
 PdfViewer.openAsset(
          'https://firebasestorage.googleapis.com/v0/b/three-6bc5c.appspot.com/o/New%20Microsoft%20Word%20Document.pdf?alt=media&token=7ce24408-c636-4fde-9f39-9e24d835fbf3',
          onError: (_) => Logger().e(_),
        ),
```

**Comment by espresso3389** [comment]
Please do `flutter clean` and run the code again.
Anyway, `PdfViewer.openAsset` does not support downloading of internet resources.

**Comment by maxzod** [comment]
now it works 
i was in a hurry that i didn't notice `openAsset`  
thanks
