### ISSUE TITLE
How to achive minScale/minZoom

### ISSUE THREAD

**Issue by sagarkardani** [espresso3389/flutter_pdf_render#39]
I want to zoom out much more and want to show small pages like this...

![20210411_200230](https://user-images.githubusercontent.com/60609139/114308229-c0177480-9b00-11eb-9f40-b6e441ebcaa0.jpg)

I tried setting minScale but it does not seems working...

How to achieve this ?

**Comment by jasonjflaherty** [comment]
You can utilize flutters InteractiveViewer to do this with PdfDocumentLoader. However, minScale doesn't seem to work. You might play with this a bit though and find a solution.

```
return InteractiveViewer(
              minScale: 0.1, //minscale doesn't seem to work.
              maxScale: 5,
              child: PdfDocumentLoader.openAsset(
                'assets/pdf.pdf,
                documentBuilder: (context, pdfDocument, pageCount) =>
                    LayoutBuilder(
                  builder: (context, constraints) => ListView.builder(
                    itemCount: pageCount,
                    itemBuilder: (context, index) => Container(
                      child: PdfPageView(
                        pdfDocument: pdfDocument,
                        pageNumber: index + 1,
                      ),
                    ),
                  ),
                ),
              ),
            );
```

**Comment by espresso3389** [comment]
FYI: [InteractiveViewer minScale property](https://api.flutter.dev/flutter/widgets/InteractiveViewer/minScale.html)

> Scale is also affected by boundaryMargin. If the scale would result in viewing beyond the boundary, then it will not be allowed. By default, boundaryMargin is EdgeInsets.zero, so scaling below 1.0 will not be allowed in most cases without first increasing the boundaryMargin.

It's very confusing enough and it's too difficult to make the pages smaller than the viewport, it's currently a limitation of Flutter's InteractiveViewer widget...
