### ISSUE TITLE
MissingPluginException(No implementation found for method data on channel pdf_render)

### ISSUE THREAD

**Issue by lazylazyllama** [espresso3389/flutter_pdf_render#4]
No matter what I do I always end up getting this error:

`E/flutter (13502): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method data on channel pdf_render)
E/flutter (13502): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter (13502): <asynchronous suspension>
E/flutter (13502): #1      PdfDocument.openData (package:pdf_render/pdf_render.dart:65:33)
E/flutter (13502): <asynchronous suspension>
E/flutter (13502): #2      _PdfDocumentLoaderState._init (package:pdf_render/pdf_render_widgets.dart:121:32)
E/flutter (13502): <asynchronous suspension>
E/flutter (13502): #3      _PdfDocumentLoaderState.initState (package:pdf_render/pdf_render_widgets.dart:79:5)
E/flutter (13502): #4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4061:58)
E/flutter (13502): #5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3912:5)
E/flutter (13502): #6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3094:14)
E/flutter (13502): #7      Element.updateChild (package:flutter/src/widgets/framework.dart:2897:12)
E/flutter (13502): #8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3954:16)
E/flutter (13502): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:3731:5)
E/flutter (13502): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2341:33)
E/flutter (13502): #11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:775:20)
E/flutter (13502): #12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:279:5)
E/flutter (13502): #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1040:15)
E/flutter (13502): #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:982:9)
E/flutter (13502): #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:898:5)
E/flutter (13502): #16     _rootRun (dart:async/zone.dart:1124:13)
E/flutter (13502): #17     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter (13502): #18     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter (13502): #19     _invoke (dart:ui/hooks.dart:249:10)
E/flutter (13502): #20     _drawFrame (dart:ui/hooks.dart:207:3)`

My layout:
````dart
PdfDocumentLoader(
        data: pdfModel.plan,
        documentBuilder: (context, pdfDocument, pageCount) => LayoutBuilder(
            builder: (context, constraints) => ListView.builder(
                itemCount: pageCount,
                itemBuilder: (context, index) => Container(
                    color: Colors.green,
                    child: PdfPageView(
                        pdfDocument: pdfDocument,
                        pageNumber: index + 1,
                        // calculateSize is used to calculate the rendering page size
                        calculateSize: (pageWidth, pageHeight, aspectRatio) =>
                            Size(
                                constraints.maxWidth - 0,
                                (constraints.maxWidth - 0) / aspectRatio)
                    )
                )
            )
        ),
      );
````

pdfModel.plan contains a uint8Array which did work on differen pdf libraries like:
https://pub.dev/packages/native_pdf_renderer#-example-tab-
but I really would prefer your library a LOT

Addiditional environment information:
`Flutter 1.10.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision f5733f7a62 (5 days ago) • 2019-09-11 21:03:42 -0700
Engine • revision 7ea9884ab0
Tools • Dart 2.5.0 (build 2.5.0-dev.4.0 be66176534)
`

**Comment by lazylazyllama** [comment]
I think it was some incompatibility with other similar plugins installed separately ... I don't geht the error anymore.

**Comment by mhmoudsabry** [comment]
so what is the solution i am getting this error
```
2020-02-10 11:09:29.611377+0200 Runner[6929:2072993] [VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method file on channel pdf_render)
#0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
<asynchronous suspension>
#1      PdfDocument.openFile (package:pdf_render/pdf_render.dart:57:33)
#2      _PdfDocumentLoaderState._init (package:pdf_render/pdf_render_widgets.dart:117:32)
#3      _PdfDocumentLoaderState.initState (package:pdf_render/pdf_render_widgets.dart:79:5)
#4      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4355:58)
#5      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#6      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#10     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#11     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#12     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#14     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#15     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#17     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#18     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#19     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#20     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)

#21     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#22     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#23     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#24     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#26     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#29     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5445:14)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#34     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#35     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#36     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#39     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#40     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#42     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4617:11)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#48     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4381:11)
#49     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#50     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#51     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#52     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4243:16)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:3947:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4206:5)
#55     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4201:5)
#56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3194:14)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:2988:12)
#58     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1288:36)
#59     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1273:20)
#60     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2412:19)
#61     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1266:11)
#62     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:354:23)
#63     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1823:58)
#64     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:875:15)
#65     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1823:13)
#66     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:343:5)
#67     RenderSliverMultiBoxAdaptor.addInitialChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:427:5)
#68     RenderSliverList.performLayout (package:flutter/src/rendering/sliver_list.dart:78:12)
#69     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#70     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:134:11)
#71     RenderSliverPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:373:11)
#72     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#73     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:410:13)
#74     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1367:12)
#75     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1285:20)
#76     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#77     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#78     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#79     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#80     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#81     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#82     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#83     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#84     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#85     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#86     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#88     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#89     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:806:17)
#90     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#91     MultiChildLayoutDelegate.layoutChild (package:flutter/src/rendering/custom_layout.dart:163:11)
#92     _ScaffoldLayout.performLayout (package:flutter/src/material/scaffold.dart:477:7)
#93     MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:232:7)
#94     RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:391:14)
#95     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#96     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#97     RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#98     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#99     _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1232:11)
#100    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#101    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#102    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#103    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#104    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#105    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#106    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#107    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
#108    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#109    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#110    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#111    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#112    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#113    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#114    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#115    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#116    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#117    RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:105:13)
#118    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#119    RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3166:14)
#120    RenderObject.layout (package:flutter/src/rendering/object.dart:1724:7)
#121    RenderStack.performLayout (package:flutter/src/rendering/stack.dart:505:15)
#122    RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1584:7)
#123    PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:844:18)
#124    RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:344:19)
#125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:774:13)
#126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:283:5)
#127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102:15)
#128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1041:9)
#129    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957:5)
#130    _rootRun (dart:async/zone.dart:1126:13)
#131    _CustomZone.run (dart:async/zone.dart:1023:19)
#132    _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#133    _invoke (dart:ui/hooks.dart:259:10)
#134    _drawFrame (dart:ui/hooks.dart:217:3)
```

**Comment by espresso3389** [comment]
Could you show me your `flutter doctor` result?

**Comment by espresso3389** [comment]
Sorry, I need the result of `flutter doctor -v`. Anyway, iOS or Android?

**Comment by mhmoudsabry** [comment]
```
macbook-pro-7:almaktab Soufian$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G3020,
    locale en-EG)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] Android Studio (version 3.3)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by mhmoudsabry** [comment]
```
 flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.14.6 18G3020,
    locale en-EG)
    • Flutter version 1.12.13+hotfix.5 at /Users/ShadyGhalab/development/flutter
    • Framework revision 27321ebbad (9 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/ShadyGhalab/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.7.5

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 33.4.1
    • Dart plugin version 182.5215
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] Connected device (1 available)
    • iPhone KFH • f3ee5337016f924c5a487d6c749f245031e67bf4 • ios • iOS 11.3.1

• No issues found!
```

**Comment by mhmoudsabry** [comment]
> Sorry, I need the result of `flutter doctor -v`. Anyway, iOS or Android?

this is flutter doctor -v

**Comment by espresso3389** [comment]
For iOS, my first guess was CocoaPods version. But 1.7.5 seems OK to me anyway.
So, the next question is, what plugins are you using on your app?

**Comment by mhmoudsabry** [comment]
this is all yaml file```
name: AlMAKTAB
description: A new Flutter project.
# file_picker:
#     git:
#       url: git://github.com/Boehrsi/plugins_flutter_file_picker
#       ref: 192_embeddingV2
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"
# dependency_overrides:
#   extended_image_library:
#     git:
#         url: https://github.com/fluttercandies/extended_image_library.git
#         ref: dev
dependencies:
  firebase_crashlytics: ^0.1.2+2
  font_awesome_flutter: ^8.5.0
  cloud_firestore: 
  firebase_auth: ^0.14.0+5
  path_provider: ^1.4.0
  file_picker: ^1.4.3+2
  image_picker:
  firebase_storage: ^3.0.6
  googleapis: any
  googleapis_auth: any
  flutter_sound: ^1.5.2
  flutter_pdfview: ^1.0.0+9
  progress_dialog: ^1.2.0
  datetime_picker_formfield: ^0.4.3
  country_code_picker: ^1.1.7
  dots_indicator: ^1.1.0
  rflutter_alert: ^1.0.3
  intl: ^0.15.7
  flutter_bloc: ^3.1.0
  flutter_genius_scan: ^3.0.8
  pdf_render: ^0.57.1
  pdf: ^1.3.24
  flutter_signature_pad: ^2.0.0+1
  flutter_material_color_picker: ^1.0.5
  auto_size_text: ^2.1.0
  image: ^2.1.4
  mime: ^0.9.6+3
  equatable: ^1.0.1 
  extended_text: ^0.6.6
  loading_animations: ^2.1.0
  easy_dialog: ^1.0.5
  device_preview: ^0.2.6
  language_pickers: ^0.1.3
  image_editor: ^0.1.6
  after_layout: ^1.0.7+2
  flutter_mailer: ^0.4.2
  flutter_email_sender: ^2.2.2
  fluttertoast: ^3.1.3
  email_validator: ^1.0.3
  flutter_xlider: ^3.0.1
  connectivity: ^0.4.6+2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
    
# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/iconWithWord.png
  color: "ffffff"
  android_disable_fullscreen: true
#   flutter_launcher_icons:
#     # path: ../

# flutter_icons:
# #  image_path: "assets/images/icon-128x128.png"
#   image_path_android: "assets/images/icon.png"
#   image_path_ios: "assets/images/icon.png"
#   android: true # can specify file name here e.g. "ic_launcher"
#   ios: true # can specify file name here e.g. "My-Launcher-Icon"
  # adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
  # adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/bottomsheet/
    - assets/images/drawer/
    - assets/images/file/
    - assets/images/filter/
    - assets/images/launcher/
    - assets/data/

  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

**Comment by mhmoudsabry** [comment]
> For iOS, my first guess was CocoaPods version. But 1.7.5 seems OK to me anyway.
> So, the next question is, what plugins are you using on your app?

any news??

**Comment by o-julio** [comment]
Kill your application in `flutter run` or vscode and restart after installing this plugin.
