### ISSUE TITLE
Screenshot parts of the PDF

### ISSUE THREAD

**Issue by deepu** [espresso3389/flutter_pdf_render#48]
Hey, firstly great plugin. it's working pretty smooth for most of what I need. 

However I am stuck when I try to capture screenshot of whatever is displaying on the screen as an image. 
I tried wrapping PDFViewer with the Screenshot plugin (https://pub.dev/packages/screenshot) but it just shows me empty screen without any text 

My code 
```
class CreateNotesView extends GetView<CreateNotesController> {
  @override
  Widget build(BuildContext context) {
    ScreenshotController screenshotController = ScreenshotController();
    return Scaffold(
      appBar: AppBar(
        title: Text('CreateNotesView'),
        centerTitle: true,
      ),
      body: Screenshot(
        controller: screenshotController,
        child: PdfViewer.openFile(
          controller.notesPdf.path,
        ),
      ),
      floatingActionButton: IconButton(
          onPressed: () {
            print('pressed');
            screenshotController.capture().then((value) {
              print('screenshot Done');
              Get.defaultDialog(
                content: Image.memory(value!)
              );
            }).catchError((onError) {
              print(onError);
            });
          },
          icon: Icon(Icons.camera)),
    );
  }
}
```

When I take screenshot it shows like this.
As you can see, the outline, borders, drop shadows et al are captured but the actual content inside the PDF is missing from the screenshot. Any tips on how to go about resolving this ? 

![IMG_9A6D6BE220D5-1](https://user-images.githubusercontent.com/55172/124712811-649d2d00-df1d-11eb-8dd4-d21595381841.jpeg)

**Comment by espresso3389** [comment]
On the bottom of [screenshot Readme](https://pub.dev/packages/screenshot),

> Platform Views are not supported. (Example: Google Maps, Camera etc)

I'm not sure what they describing by the word "Platform Views" but it does not seem to support [Texture](https://api.flutter.dev/flutter/widgets/Texture-class.html), which is heavily used in pdf_render plugin:

- [screenshot #14: ScreenShot from video_player](https://github.com/SachinGanesh/screenshot/issues/14)
- [flutter #25306: Cannot take screenshot for platform-views by using RepaintBoundary?](https://github.com/flutter/flutter/issues/25306)

But I'm not sure what really impacts on the screenshot feature so far.

**Comment by espresso3389** [comment]
By the way, if you just need some kind of document image, pdf_render also provides low and raw level API that renders page image one by one.

- [PDF rendering APIs](https://pub.dev/documentation/pdf_render/latest/#pdf-rendering-apis)

It can generate [dart:ui Image](https://api.flutter.dev/flutter/dart-ui/Image-class.html) so that it can be saved to PNG file or anything:

```dart
...
final pageImage = await page.render();
final image = await pageImage.createImageDetached();
final pngData = await image.toByteData(ImageByteFormat.png);
```

**Comment by deepu** [comment]
Thanks this helped. 
I rendered pngdata and now able to take screenshot of that Image

Thanks a ton again
