### ISSUE TITLE
Zoom feature

### ISSUE THREAD

**Issue by lazylazyllama** [espresso3389/flutter_pdf_render#5]
I really like your pdf library!

It does everything exactly the way I want it too except one thing:

I really need the possibility to zoom into my files. 

Is there a way? If not: Will there be one in the near future?

**Comment by espresso3389** [comment]
I'm planning it now but no estimate so far.

Basically, I think it's possible to implement such by using [CustomPainter](https://api.flutter.dev/flutter/rendering/CustomPainter-class.html) and existing [PdfPageImage](https://pub.dev/documentation/pdf_render/latest/pdf_render/PdfPageImage-class.html).

**Comment by dariotrombello** [comment]
Any updates on this?

**Comment by KorbinianMossandl** [comment]
you can make your pdf pages zoomable like any other widgets:
https://stackoverflow.com/questions/56423707/flutter-zoomable-widget

Did it in my app for pdf pages and it works quite well.

**Comment by espresso3389** [comment]
[0.66.0](https://pub.dev/packages/pdf_render/versions/0.66.0) (b89a1d6dc239d205bbf3366a64cd0d7a5f15edf1) is the first release that supports pinch-zoom enabled [PdfViewer](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets2/PdfViewer-class.html).
