### ISSUE TITLE
Hang using PdfDocumentLoader (0.64.1 on Android)

### ISSUE THREAD

**Issue by tony123S** [espresso3389/flutter_pdf_render#51]
I using this code to display pdf file from network url, but it seems like consumer lot of space?

`Background young concurrent copying GC freed 364(78KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 80MB/80MB, paused 17.436ms total 46.478ms
`
**Code**

```
PdfDocumentLoader(
                                pageNumber: 1,
                                data: snapshot.data,
                              )
```

**Comment by espresso3389** [comment]
Android or iOS?
And please give me more info about your PDF file if possible.

PDF loading process depends on platform specific PDF renderers; [PdfRenderer](https://developer.android.com/reference/android/graphics/pdf/PdfRenderer) on Android and [https://developer.apple.com/documentation/coregraphics/cgpdfdocument](CGPDFDocument) on iOS and I cannot determine what causes the actual issue.

Basically, [PdfDocumentLoader.openData](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets/PdfDocumentLoader/PdfDocumentLoader.openData.html) takes `Uint8List` data and it will be internally memory-copied at least twice for platform channel serialization process. If the PDF file is too large, the cost could not be ignored...

One apparent workaround is that saving the downloaded data to some temporary file and loading it with [PdfDocumentLoader.openFile](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets/PdfDocumentLoader/PdfDocumentLoader.openFile.html).

**Comment by tony123S** [comment]
I'm using Android.

```
FutureBuilder(
                future: http.get(url),
                builder: (context, snapshot) {
                  switch (snapshot.connectionState) {
                    case ConnectionState.done:
                      return InkWell(
                          onTap: () {
                               ......
                          },
                          child: Container(
                              padding: EdgeInsets.zero,
                              height: 150,
                              width: 150,
                              child: PdfDocumentLoader(
                                pageNumber: 1,
                                data: snapshot.data.bodyBytes,
                              )));
                      break;

                    case ConnectionState.waiting:
                      return CircularProgressIndicator();
                      break;

                    default:
                      return Text("Error");
                  }
                });
```

**Comment by espresso3389** [comment]
There is [a very good introduction for supporing networking](https://github.com/espresso3389/flutter_pdf_render#missing-network-support) using [flutter_cache_manager](https://pub.dev/packages/flutter_cache_manager):

```dart
FutureBuilder<File>(
  future: DefaultCacheManager().getSingleFile(
    'https://github.com/espresso3389/flutter_pdf_render/raw/master/example/assets/hello.pdf'),
  builder: (context, snapshot) => snapshot.hasData
    ? PdfViewer.openFile(snapshot.data!.path)
    : Container( /* placeholder */),
)
```

Is it suitable for your case?

**Comment by tony123S** [comment]
my flutter version is 1.22.6. I get cannot resolved for PdfViewer.

**Comment by espresso3389** [comment]
Wow...
But basically, what you should do is once caching the downloaded file to file and use file version of PdfDocumentLoader.

**Comment by tony123S** [comment]
ok, thanks for you suggestion..I try it now  :)

**Comment by tony123S** [comment]
I notice it will hang a while when setState or onTap is called. Maybe FutureBuilder keep calling the internally memory-copied I guess.

**Comment by espresso3389** [comment]
So which version of pdf_render are you using?

**Comment by tony123S** [comment]
I didn't specific the version because it will throws me dependency error. I might need to take some time to upgrade my flutter version...

**Comment by espresso3389** [comment]
Please check your `pubspec.lock` file to see the actual version of pdf_render plugin loaded.

**Comment by tony123S** [comment]
pdf_render:
    dependency: "direct dev"
    description:
      name: pdf_render
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.64.1"

**Comment by espresso3389** [comment]
There seems several memory efficiency updates since 0.64.1. I think [0.66.2](https://pub.dev/packages/pdf_render/versions/0.66.2) (or [0.69.0](https://pub.dev/packages/pdf_render/versions/0.69.0))is better than 0.64.1.
Could you check whether these builds break your build or not?

**Comment by espresso3389** [comment]
To reduce rebuilding of PdfDocumentLoader, you can use PdfPageView like this:

```dart
FutureBuilder(
  future: http.get(url),
  builder: (context, snapshot) {
    switch (snapshot.connectionState) {
      case ConnectionState.done:
        // PdfDocumentLoader can be used with PdfPageView
        // loading document outside InkWell to reduce reloading whole the document
        return PdfDocumentLoader(
          data: snapshot.data.bodyBytes,
          documentBuilder: (context, pdfDocument, pageCount) => InkWell(
            onTap: () {
                  ......
            },
            child: Container(
              padding: EdgeInsets.zero,
              height: 150,
              width: 150,
              child: PdfPageView(
                    pdfDocument: pdfDocument,
                    pageNumber: 1)
          )
        );
        break;

      case ConnectionState.waiting:
        return CircularProgressIndicator();
        break;

      default:
        return Text("Error");
    }
  });
```

**Comment by tony123S** [comment]
Hi, I appreciate your answer. I using 0.69.0 now but it still freeze. 

Everytime I select a pdf file and load it into GridView, it starts to freeze. 

import 'dart:io';

import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:xxx/listener/image_picker_listener.dart';
import 'package:pdf_render/pdf_render_widgets2.dart';
import '../global.dart';
import 'dialog/image_picker_dialog.dart';

class CreateCase extends StatefulWidget {
  static const ROUTE = '/create';

  @override
  State<StatefulWidget> createState() => _CreateCaseState();
}

class _CreateCaseState extends State<CreateCase> with ImagePickerListener {
  List<String> list = List<String>();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(title: Text("Testing")),
        body: SingleChildScrollView(
            child: Column(
          children: [
            textView(),
            SizedBox(height: 15),
            textView(),
            SizedBox(height: 15),
            textView(),
            SizedBox(height: 15),
            textView(),
            _showListView()
          ],
        )));
  }

  Widget _showListView() {
    return GridView.builder(
      shrinkWrap: true,
      physics: NeverScrollableScrollPhysics(),
      gridDelegate: new SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        mainAxisSpacing: 5.0,
        crossAxisSpacing: 5.0,
      ),
      itemCount: list.length + 1,
      itemBuilder: (BuildContext context, int index) => new Padding(
          padding: const EdgeInsets.all(5.0),
          child: (index < list.length)
              ? Stack(children: <Widget>[
                  Padding(
                      padding: EdgeInsets.all(10),
                      child: PdfDocumentLoader(
                          filePath: list[index],
                          documentBuilder: (context, pdfDocument, pageCount) =>
                              InkWell(
                                  onTap: () {},
                                  child: Container(
                                      padding: EdgeInsets.zero,
                                      height: 150,
                                      width: 150,
                                      child: PdfPageView(
                                          pdfDocument: pdfDocument,
                                          pageNumber: 1))))),
                  Positioned(
                    right: 12.0,
                    top: 5.0,
                    child: Container(
                      width: 20.0,
                      height: 20.0,
                      child: FloatingActionButton(
                        heroTag: index.toString(),
                        child: const Icon(
                          Icons.close,
                          color: Colors.red,
                        ),
                        backgroundColor: Colors.transparent,
                        onPressed: () {
                          setState(() {
                            list.removeAt(index);
                          });
                        },
                      ),
                    ),
                  )
                ])
              : InkWell(
                  onTap: () {
                    Global().hideKeyboard(context);
                    showDialog(
                        context: context,
                        builder: (_) => ImagePickerDialog(this));
                  },
                  child: Padding(
                      padding: EdgeInsets.all(10),
                      child: Container(
                        width: 150.0,
                        height: 150.0,
                        decoration: BoxDecoration(
                            border: Border.all(color: Colors.grey)),
                        child: Icon(Icons.camera_alt_outlined),
                      )))),
    );
  }

  Widget textView() {
    return Padding(
      padding: EdgeInsets.all(10),
      child: TextField(
        decoration: InputDecoration(
          border: OutlineInputBorder(
              borderRadius: const BorderRadius.all(const Radius.circular(5.0))),
          contentPadding: EdgeInsets.all(10),
          hintText: "Select an option",
        ),
      ),
    );
  }

  @override
  userImage(File image) async {
    list.add(image.path);
  }
}

**Comment by tony123S** [comment]
There nothing wrong with this plugin. I should run in isolate thread to avoid hanging.
I have open an issue for this. Thanks.

https://github.com/flutter/flutter/issues/87704
