### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by albatrosify** [espresso3389/flutter_pdf_render#56]
Exception:
```Null check operator used on a null value```

Stack trace:
```#0 _PdfViewerState._updatePageState (package:pdf_render/pdf_render_widgets.dart:1121)```
<asynchronous suspension>

Version 1.0.12

**Comment by espresso3389** [comment]
On which platform are you using?

**Comment by albatrosify** [comment]
This issue has been reported on android. However I only use this package on android.

**Comment by espresso3389** [comment]
OK, I'll investigate the issue further.

**Comment by estevez-dev** [comment]
I'm having the same issue using `PdfViewer.openData` in `FutureBuilder`. Here is a code:

```dart
SafeArea(
      child: FutureBuilder<Uint8List>(
        future: widget.file.readAsBytes(),
        builder: (context, snapshot) => snapshot.hasData
            ? PdfViewer.openData(snapshot.data!)
            : const CircularProgressIndicator(),
      ),
    )
```

And the error:

```
flutter: >> UNHANDLED ERROR! <<
flutter: Null check operator used on a null value
flutter: #0      _PdfDocumentAwaiter.getValue (package:pdf_render/pdf_render_widgets.dart:76:19)
<asynchronous suspension>
#1      _PdfViewerState._load (package:pdf_render/pdf_render_widgets.dart:1063:12)
<asynchronous suspension>
flutter: >> UNHANDLED ERROR! <<
flutter: Null check operator used on a null value
flutter: #0      _PdfDocumentAwaiter.getValue (package:pdf_render/pdf_render_widgets.dart:76:19)
<asynchronous suspension>
#1      _PdfViewerState._checkUpdates (package:pdf_render/pdf_render_widgets.dart:1035:10)
<asynchronous suspension>
```

**Comment by estevez-dev** [comment]
> I'm having the same issue using `PdfViewer.openData` in `FutureBuilder`. Here is a code:
> 
> ```dart
> SafeArea(
>       child: FutureBuilder<Uint8List>(
>         future: widget.file.readAsBytes(),
>         builder: (context, snapshot) => snapshot.hasData
>             ? PdfViewer.openData(snapshot.data!)
>             : const CircularProgressIndicator(),
>       ),
>     )
> ```
> 
> And the error:
> 
> ```
> flutter: >> UNHANDLED ERROR! <<
> flutter: Null check operator used on a null value
> flutter: #0      _PdfDocumentAwaiter.getValue (package:pdf_render/pdf_render_widgets.dart:76:19)
> <asynchronous suspension>
> #1      _PdfViewerState._load (package:pdf_render/pdf_render_widgets.dart:1063:12)
> <asynchronous suspension>
> flutter: >> UNHANDLED ERROR! <<
> flutter: Null check operator used on a null value
> flutter: #0      _PdfDocumentAwaiter.getValue (package:pdf_render/pdf_render_widgets.dart:76:19)
> <asynchronous suspension>
> #1      _PdfViewerState._checkUpdates (package:pdf_render/pdf_render_widgets.dart:1035:10)
> <asynchronous suspension>
> ```

So my issue was resolved by running `pod install` and rebuilding the app )

Still there is an issue in a plugin:

```dart
/// Exception-proof await/cache mechanism on [PdfDocument] Future.
class _PdfDocumentAwaiter {
  _PdfDocumentAwaiter(this._docFuture, {this.onError});

  final FutureOr<PdfDocument> _docFuture;
  final OnError? onError;
  PdfDocument? _cached;

  Future<PdfDocument> getValue() async {
    if (_cached == null) {
      try {
        _cached = await _docFuture;
      } catch (e) {
        onError?.call(e);
      }
    }
    return _cached!;
  }
}
```

The method `getValue()` will try to return `null` in case of any exception.
