### ISSUE TITLE
Web: PDF rendering distorted since Flutter Master 2.6.0-12.0.pre.674

### ISSUE THREAD

**Issue by zambetpentru** [espresso3389/flutter_pdf_render#60]
Hi,

FYI to save time in case anyone else comes across this, I found that since Flutter version 2.6.0-12.0.pre.674 the PDF rendering is distorted and upside down.  https://github.com/flutter/flutter/issues/93615

**Comment by espresso3389** [comment]
Wow, I confirmed the issue. Interesting bug...

![image](https://user-images.githubusercontent.com/1311400/141994618-7f36e73f-9038-4cb1-80d7-fc4e465541c2.png)

**Comment by espresso3389** [comment]
NOTE: I confirmed that the plugin works correctly on 2.6.0-12.0.pre.670 ([858a328712](https://github.com/flutter/flutter/commit/858a328712)) at least.
```
[✓] Flutter (Channel unknown, 2.6.0-12.0.pre.670, on Microsoft Windows [Version 10.0.22504.1000], locale ja-JP)
    • Flutter version 2.6.0-12.0.pre.670 at C:\Work\flutter
    • Upstream repository unknown
    • Framework revision 858a328712 (9 days ago), 2021-11-09 22:22:14 -0800
    • Engine revision 76bf5a1ad0
    • Dart version 2.15.0 (build 2.15.0-285.0.dev)
```

**Comment by espresso3389** [comment]
https://github.com/flutter/flutter/issues/93615#issuecomment-973820194

I've created [a simple repro of the issue](https://dartpad.dev/?id=84269f8fa00ff580485e244c66d923c7&null_safety=true).

**Comment by zambetpentru** [comment]
Hi,

While it's confirmed that the reversal of the array is intended, here are two parts that make it work for me (there are probably some other updates for code paths I don't use):

pdf_texture_web.dart
![image](https://user-images.githubusercontent.com/81489824/146060517-2b978b30-052e-4e08-8b96-ab32958a080d.png)

pdf_render_web_plugin.dart
![image](https://user-images.githubusercontent.com/81489824/146060588-370341e8-a18a-4557-bd28-71184ca07573.png)

**Comment by Vannak1111** [comment]
Hi I am Test the example in the package but is not work 
![PDF](https://user-images.githubusercontent.com/95061289/150065882-7ab47427-3ce7-459b-8b64-8800fdb1ee3b.JPG)
![d](https://user-images.githubusercontent.com/95061289/150066142-dba42bbf-b58c-4f09-acf1-f6e8c9601f04.JPG)

Thank

**Comment by espresso3389** [comment]
Could you give my your environment info?
- Flutter version (`flutter doctor`)
- Browser version
- pdf_render version (possibily the latest?)

And, also, could you please check DevTools console log?

**Comment by espresso3389** [comment]
@Vannak1111 Mmm, I think it's not related the issue discussed here. Please file a new issue for your issue.

**Comment by Vannak1111** [comment]
1.flutter doctor
![1](https://user-images.githubusercontent.com/95061289/150075149-06caaf16-42a5-4744-8e6f-f220f96c109f.JPG)

2.Browser version last version

**Comment by Vannak1111** [comment]
thank

**Comment by espresso3389** [comment]
@Vannak1111 Again, could you please file a new issue? And, "last version" does not make sense. Please describe the exact version.

**Comment by espresso3389** [comment]
Wow, I finally found that the issue is officially documented:
- [Raw images on Web uses correct origin and colors](https://docs.flutter.dev/release/breaking-changes/raw-images-on-web-uses-correct-origin-and-colors)
