### ISSUE TITLE
1.0.18 enabled WebGL

### ISSUE THREAD

**Issue by zambetpentru** [espresso3389/flutter_pdf_render#63]
Hi,

I noted on 1.0.18 that you enabled WebGL, can you share a little about what that does? I was looking into it a few weeks back and it seemed like that was removed from PDF.js (as it only helped with certain use cases and was never updated since 2014) https://github.com/mozilla/pdf.js/issues/5161

**Comment by espresso3389** [comment]
I meant nothing but just added the flag. But it does not seem any meaningful behavior changes... OK, I just removed it on e9a10d1a21958484dfde817a301c81cb944ca93b.
