### ISSUE TITLE
[Android] Not all pages shown from the PDF

### ISSUE THREAD

**Issue by deakjahn** [espresso3389/flutter_pdf_render#68]
I have some four-page PDFs (I'd be glad to send them to you but is there any other way than to upload here? Not very secret but still, I wouldn't want to leave them here) that display as two pages, then I get the error message:

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: RangeError (index): Invalid value: Not in inclusive range 0..1: 2
#0      List._setIndexed (dart:core-patch/array.dart:121:48)
#1      List.[]= (dart:core-patch/array.dart:116:5)
#2      _PdfDocumentLoaderState._setPageSize (package:pdf_render/pdf_render_widgets.dart:197:24)
#3      _PdfPageViewState._init (package:pdf_render/pdf_render_widgets.dart:331:26)
<asynchronous suspension>

LateInitializationError: Field '_cached@1088039934' has not been initialized.
```

So, part of the plugin is aware that there are pages beyond the second, yet there will be a display error. This seems to suggest that all this might be independent from the PDF itself (those are guaranteed to be OK, can be viewed in other Flutter PDF viewers, too, as well as on any other platform).

The viewer comes straight from your README samples:

      return PdfDocumentLoader.openAsset(
        'assets/$_file',
        documentBuilder: (context, pdf, pageCount) => LayoutBuilder(
          builder: (context, constraints) => ListView.builder(
            scrollDirection: Axis.horizontal,
            itemCount: pageCount,
            itemBuilder: (context, index) => PdfPageView(
              pdfDocument: pdf,
              pageNumber: index + 1,
            ),
          ),
        ),
        onError: (error) => print(error.toString()),
      );

**Comment by deakjahn** [comment]
I'm investigating. I tried some display:

    void _setPageSize(int pageNumber, Size? size) {
      print("pageNumber=$pageNumber");
      _lastPageSize = size;
      print("pageCount=${_doc!.pageCount}");
      if (pageNumber > 0 && pageNumber <= _doc!.pageCount) {
        _cachedPageSizes ??= List<Size?>.filled(_doc!.pageCount, null);
        _cachedPageSizes![pageNumber - 1] = size;
      }
    }

And `page`Number and `pageCount` are correct but the cache is small. The reason will be that I display _different_ PDFs one after the other and if a first show a 2-page one, then a 4-page one, the cache gets created for the first one and will be unsufficient later.

**Comment by deakjahn** [comment]
By the way, I still get:

    LateInitializationError: Field '_cached@1088039934' has not been initialized.

but that will be a different problem:

    late PdfDocument _cached;

**Comment by espresso3389** [comment]
@deakjahn
So you're talking about switching some PDF with another?

For the sample file, if possible, please send them to `espresso3389 _at_ gmail.com`.

**Comment by deakjahn** [comment]
Yes. I have an app with two dozen PDFs and I always show the the user selects from a menu. I can send you the PDF but it doesn't depend on the PDF at all, it's the cache, with my changed line above it works now.

**Comment by espresso3389** [comment]
I see, it is apparently a bug of pdf_render and I'll investigate the issue futher.

And, I think (it means not tested), in the case, specifying unique `key` to your `PdfDocumentLoader.openAsset` call may get around the issue:

```dart
return PdfDocumentLoader.openAsset(
    'assets/$_file',
    key: Key('assets/$_file'),
    documentBuilder: (context, pdf, pageCount) => LayoutBuilder(
      builder: (context, constraints) => ListView.builder(
        scrollDirection: Axis.horizontal,
        itemCount: pageCount,
        itemBuilder: (context, index) => PdfPageView(
          pdfDocument: pdf,
          pageNumber: index + 1,
        ),
      ),
    ),
    onError: (error) => print(error.toString()),
  );
```

**Comment by deakjahn** [comment]
Yep, I actually used that approach for another plugin, this might be another solution. I'll test.

In the meantime, I think I fixed the late initialization error, too:

```
class _PdfDocumentAwaiter {
  _PdfDocumentAwaiter(this._docFuture, {this.onError});

  final FutureOr<PdfDocument> _docFuture;
  final OnError? onError;
  PdfDocument? _cached;

  Future<PdfDocument> getValue() async {
    if (_cached == null) {
      try {
        _cached = await _docFuture;
      } catch (e) {
        onError?.call(e);
      }
    }
    return _cached!;
  }
}
```

**Comment by deakjahn** [comment]
Yep, the key approach works all right. But even then, the error message could be better (try-catch that code and say something better instead of the range error, something about cache reuse). And you could add the idea to the README, too. :-)

**Comment by deakjahn** [comment]
@espresso3389 While we're here, I'll ask if you have a suggestion to make a `ListView/GridView` setup with pinch zoom. The plain `PdfViewer` is nice but it doesn't support horizontal scrolling, only vertical. I can use a custom view to provide horizontal, or even 2x2 pages for page pairs, but I don't have zoom then.

**Comment by espresso3389** [comment]
@deakjahn 
> I'll ask if you have a suggestion to make a ListView/GridView setup with pinch zoom. The plain PdfViewer is nice but it doesn't support horizontal scrolling, only vertical. I can use a custom view to provide horizontal, or even 2x2 pages for page pairs, but I don't have zoom the

Yes, I want to do that. [InteractiveViewer](https://api.flutter.dev/flutter/widgets/InteractiveViewer/InteractiveViewer.html) is not always the optimal solution and I think there should be another.
But it's not so easy to implement such one (al least for me)...

**Comment by deakjahn** [comment]
@espresso3389 2x2 would be optimal for me but even a horizontal `PdfViewer` would do now.

**Comment by deakjahn** [comment]
By Jove, now that I looked more deeply into your code, this is much more ambitious than I first thought. :-) I thought you just delegated the work (in the "simple" case, `PdfViewer`) to an underlying platform package. But no, you only use the platform renderer (unfortunately, it only converts to bitmaps, not vector) and craft your own viewer completely. This means that all these could be solved...

**Comment by deakjahn** [comment]
Now I see, the `layoutPages` func could be the solution to my case.

I'd suggest to cover the basic use case in the plugin, still. Adding an `Axis? scrollDirection` to `PdfViewerParams`, and turning `iterateLaidOutPages` into two versions, vertical and horizontal. I started to add this code but I don't want to commit it now because it would immediately appear in this PR.

**Comment by deakjahn** [comment]
No, I added it directly now.

**Comment by espresso3389** [comment]
I'm investigating the issue now.

**Comment by deakjahn** [comment]
And using the page matrix to switch to the first page solved my zooming issues:

    await controller.goTo(destination: controller.calculatePageFitMatrix(pageNumber: 1));
