### ISSUE TITLE
Blank screen on flutter 2.10

### ISSUE THREAD

**Issue by BrunoAlm** [espresso3389/flutter_pdf_render#73]
Worked fine until the update

> Flutter Doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [versÃ£o 10.0.22543.1000], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.7)
[√] Android Studio (version 4.2)
[√] VS Code (version 1.64.0)
[√] Connected device (3 available)
[√] HTTP Host Availability
• No issues found!

 `PdfDocumentLoader.openAsset(
          'assets/pdf/janfie.pdf',
          documentBuilder: (context, pdfDocument, pageCount) => LayoutBuilder(
            builder: (context, constraints) => ListView.builder(
              scrollDirection: Axis.vertical,
              itemCount: pageCount,
              itemBuilder: (context, index) => Container(
                margin: EdgeInsets.all(2),
                padding: EdgeInsets.all(0),
                color: Colors.black12,
                child: PdfPageView(
                  pdfDocument: pdfDocument,
                  pageNumber: index + 1,
                ),
              ),
            ),
          ),
        ),`

**Comment by espresso3389** [comment]
Running sample code on Android?
Do you see any warnings or errors on your console?

**Comment by BrunoAlm** [comment]
I forgot rs.

Running on Web.
Console error: Uncaught ReferenceError: pdfjsLib is not defined
![image](https://user-images.githubusercontent.com/65208006/152624959-b8296228-89ba-4440-96c2-d52b67043994.png)

**Comment by BrunoAlm** [comment]
It was my network... with vpn it works...
