### ISSUE TITLE
Failed to activate protocol version: "sourceDirectory" is not a directory.

### ISSUE THREAD

**Issue by Zhangyc1998** [espresso3389/flutter_pdf_render#79]
![image](https://user-images.githubusercontent.com/57214081/162657135-ca517851-65d1-498d-bc58-1f950b7938d6.png)
How can I fix this problem？please tell me if you know

**Comment by espresso3389** [comment]
The log indicates that aemeabi-v7a (32-bit ARM) build failed. Seems to be a NDK or related issue I guess.

**Comment by Zhangyc1998** [comment]
> The log indicates that aemeabi-v7a (32-bit ARM) build failed. Seems to be a NDK or related issue I guess.

clone your code it can run,  new project  dependencies pdf_render1.0.23，it also tip this "Failed to activate protocol version: "sourceDirectory" is not a directory". but dependencies  the flutter_pdf_render it  can work. i found dependencies pdf_render1.0.23 cmake floder lost something in Flutter Plugins.
![image](https://user-images.githubusercontent.com/57214081/162695321-7dbc5b86-ba81-4eae-86cc-a889261191d9.png)
 i guess my dart  environment might have something problem。 thanks your guess😁

**Comment by Zhangyc1998** [comment]
> The log indicates that aemeabi-v7a (32-bit ARM) build failed. Seems to be a NDK or related issue I guess.
the problem casused by my user Name have some chinese charater
