### ISSUE TITLE
PDF file does not crop out print margins on Native (works on Web)

### ISSUE THREAD

**Issue by zambetpentru** [espresso3389/flutter_pdf_render#88]
Hi,

Web (and it seems all the pdf readers I've tried):
![image](https://user-images.githubusercontent.com/81489824/190578654-0c6a5a83-9242-4739-9805-447b7dd712cf.png)

Native (iPAD in this case):
![image](https://user-images.githubusercontent.com/81489824/190578435-d19076e5-7ebf-4a54-9b6c-0749a6e46627.png)

[Sample-4-5.pdf](https://github.com/espresso3389/flutter_pdf_render/files/9581549/Sample-4-5.pdf)

Any ideas if there is a flag somewhere to do this?

**Comment by zambetpentru** [comment]
Hi, I had a closer look and found the required changes:

In Android update file PdfRenderPlugin.kt: 
Change RENDER_MODE_FOR_DISPLAY to RENDER_MODE_FOR_PRINT

In iOS update SwiftPdfRenderPlugin.swift:
Change .mediaBox to .cropBox

**Comment by espresso3389** [comment]
[1.3.3](https://pub.dev/packages/pdf_render/versions/1.3.3) is just released!
