### ISSUE TITLE
Y-axis flipped on iOS (or Android)

### ISSUE THREAD

**Issue by bastibense** [espresso3389/flutter_pdf_render#9]
I did a few tests with this package and think I found a bug.

The API for `render()` does not behave the same way on iOS compared to Android.

When supplying a render sub-rectangle, the Y coordinate on Android origins from the top-left corner of the coordinate system. On iOS this is inverted and starts at the bottom-left corner.

Result is, that when rendering a part of a PDF file on both platforms, you'll get different results.

Worked around this by using a platform-check, but I'd assume that wasn't the plan. Also this is not documented anywhere, so I assume this is a bug.

Thanks!

**Comment by espresso3389** [comment]
It seems to be an issue on handling PDF rotation. I should investigate it further...
