### ISSUE TITLE
pdfium based renderer for Windows, Linux, and Android

### ISSUE THREAD

**Issue by espresso3389** [espresso3389/flutter_pdf_render#93]
In theory, many of issues are fixed by introducing pdfium based render:

- Replacing Android PdfRenderer with pdfium #92
- Not shows the pdf signed document on Android and IOS #91
- Add a way to select and copy text #90
- Landscape Oriented PDF ist rendered in Portait on a Landscape Builder #52 (Maybe PdfRenderer is changed on Android update)
- Need support of /Annots #43
- Windows/Linux support #40
- Read password protected files? #1

**Comment by espresso3389** [comment]
Currently, everything is half-done state; no progress on my project [sobar_pdf](https://github.com/espresso3389/sobar_pdf) because I'm too much busy... 😭 Ababababababa

**Comment by naoufalzerai** [comment]
hello,
any news on [sobar_pdf](https://github.com/espresso3389/sobar_pdf) :cry:

**Comment by Aruljebaraj** [comment]
Need support for windows

**Comment by espresso3389** [comment]
@Aruljebaraj Use [pdfrx](https://pub.dev/packages/pdfrx) instead. It supports Windows.
